### ISSUE TITLE
Ultibo Road Map

### ISSUE THREAD

**Issue by markfirmware** [markfirmware/bare-metal-gophers#1]
- [ ] Rule out infeasibility
- [ ] ...
- [ ] Reproduce working state
    - [x] https://github.com/achilleasa/bare-metal-gophers/issues/1
    - [ ] run in x86/qemu
- [ ] move to arm iso, run in vpb/qemu (an arm platform)
- [ ] convert to .img format, run as kernel in vpb/qemu using -kernel switch
- [ ] run as kernel on rpi
- [ ] provide 128MB from ultibo in one large segment for go runtime to manage itself
- [ ] implement interface to ultibo to obtain threads for goroutines
- [ ] implement interface to ultibo for networking
- [ ] implement interface to ultibo for test display and keyboard input
- [ ] ...
- [ ] **Goal** Load the [ngrok2](https://ngrok.com) client into [ultibo](http://ultibo.org) and run it in an ultibo thread
